apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-api
  namespace: production
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask-api
  template:
    metadata:
      labels:
        app: flask-api
    spec:
      imagePullSecrets:
        - name: gitlab-registry-secret
      containers:
        - name: flask-api
          image: registry.internal.uia.no/ikt206-g-25v-devops/group22/flask:latest
          ports:
            - containerPort: 5000
          env:
            - name: FLASK_ENV
              value: "production"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: postgres-production-secret
                  key: DATABASE_URL
